[package]
name = "btf-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
# btf = "0.5.1"
btfdump = "0.0.1"
memmap = "0.7.0"
object = "^0.11.0"
# elf = "0.7.1"
